/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo_object_classes;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.io.*;

class CellPhoneOneTest {
    @Test void testCellPhoneOne() {
        CellPhoneOne p1, p2;
        p1 = new CellPhoneOne();
        p1.phoneNumber = "123-456-7890";
        p2 = new CellPhoneOne();
        p2.phoneNumber = "123-456-7891";

        PrintStream originalOut = System.out;
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        System.setOut(new PrintStream(bos));
        p1.callNumber(p2);
        assertEquals("Calling number 123-456-7891" + 
            System.getProperty("line.separator"), bos.toString());
        System.setOut(originalOut);
    }
}
