/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo_object_classes;

/**
   The CellPhoneOne class describes the characteristics of a cell phone (first draft). 
*/
public class CellPhoneOne {
    // Fields
    public double[] dims; // dimensions of the phone, length and width, respectively
    public String color;  // color of the phone   
    public String phoneNumber; //
    /**
       The callNumber method will attemt to call an external number.
       @param number The number to be called.
    */
    public void callNumber(CellPhoneOne cp) {
        System.out.println("Calling number " + cp.phoneNumber);
    }
  }